return {
	Accent = Color3.fromRGB(71, 102, 71),

	AcrylicMain = Color3.fromRGB(20, 20, 20),
	AcrylicBorder = Color3.fromRGB(40, 40, 40), 
	AcrylicGradient = ColorSequence.new(Color3.fromRGB(30, 30, 30), Color3.fromRGB(10, 10, 10)),
	AcrylicNoise = 0.8,

	TitleBarLine = Color3.fromRGB(90, 90, 90),
	Tab = Color3.fromRGB(71, 102, 71),

	Element = Color3.fromRGB(71, 102, 71),
	ElementBorder = Color3.fromRGB(50, 50, 50),
	InElementBorder = Color3.fromRGB(80, 80, 80),
	ElementTransparency = 0.75,

	ToggleSlider = Color3.fromRGB(71, 102, 71),
	ToggleToggled = Color3.fromRGB(255, 255, 255),

	SliderRail = Color3.fromRGB(160, 160, 160),

	DropdownFrame = Color3.fromRGB(30, 30, 30),
	DropdownHolder = Color3.fromRGB(50, 50, 50),
	DropdownBorder = Color3.fromRGB(71, 102, 71),
	DropdownOption = Color3.fromRGB(71, 102, 71),

	Keybind = Color3.fromRGB(71, 102, 71),

	Input = Color3.fromRGB(71, 102, 71),
	InputFocused = Color3.fromRGB(0, 0, 0),
	InputIndicator = Color3.fromRGB(88, 127, 64),

	Dialog = Color3.fromRGB(30, 30, 30),
	DialogHolder = Color3.fromRGB(45, 45, 45),
	DialogHolderLine = Color3.fromRGB(71, 102, 71),
	DialogButton = Color3.fromRGB(30, 30, 30),
	DialogButtonBorder = Color3.fromRGB(53, 94, 59),
	DialogBorder = Color3.fromRGB(70, 70, 70),
	DialogInput = Color3.fromRGB(40, 40, 40),
	DialogInputLine = Color3.fromRGB(53, 94, 59),
	
	Text = Color3.fromRGB(255, 255, 255),
	SubText = Color3.fromRGB(170, 170, 170),
	Hover = Color3.fromRGB(71, 102, 71),
	HoverChange = 0.08
}
